Fix build_start file in finish command
honeycombio/buildevents-orb pull request #14
Opened 2019-08-14 15:10 UTC by PChambino

Most people should be using the watch command anyway, but I was reading through the source and I noticed that the `start_build` file in the `finish` command seems to be wrong. Possibly an oversight in #13.

As an extra thing, I believe the PATH doesn't need to have two directories since the binaries are only in `/tmp/be/...`, right?

We are not using the `finish` command but if someone is, it is probably not sending the duration... 🤔

2019-08-15 09:44 UTC, PChambino commented
Actually, I just realised that the `finish` command is even more broken now, because the `build_start` file is saved to the cache, so the file actually corresponds to the time the cache was saved, not the time the build started... So this may need a different solution. 🤔 

I noticed this because I am trying to get a "time to deploy" metric, because our workflow may do other things after the deploy step, so the workflow duration is not a good metric. Also, if you need to retry the workflow, calculating the time since the first run of the workflow until it finally deployed it is an interesting metric to have. :)

2019-08-15 14:29 UTC, PChambino commented
Ok. It now uses the cache like it was an workspace, by using the workflow id in the cache key. This ensures that the build_start file actually belongs to this workflow. Otherwise you can restore a random one.

Plus, if a workflow is re-run from failed, buildevents needs to be setup again for the executables and for the build_start file.

I will try to use these changes of the orb at carwow if I can figure out how to do that...

2019-08-21 18:50 UTC, maplebed commented
Part of the goal of switching to using a cache was to avoid re-downloading the buildevent binary on every build - using the version of the buildevent download as the cache key was a way to force re-download when buildevents gets a new version. 

This puts two different things in the cache - buildevents (which should be kept between builds) and the `build_start` time, which should _not_ be kept. I think we need to separate those into two different places.

Should we use a workspace for the `build_start` time and a cache for the `buildevents` binary? That's the right labeled use for each, but will it reintroduce the performance issues that were the reason behind #13? I don't think it will! The workspace will only be needed for the `finish` command, so it won't have the same effect as the previous configuration where the workspace was loaded for every job. 

I think that's our way forward: separate the saved binaries from the saved build start time.
* put the start time in a workspace
* put the binaries in a cache (with a cache key based on the buildevents version)

2019-08-21 18:58 UTC, maplebed commented
The multiple directories in the `PATH` was left over from the previous use of workspaces. Thanks for catching that and pulling it out! (details - the path to which the binaries were downloaded was different from the path at which the workspace was restored, so depending on whether the binary was used in the same or a different job from where it was downloaded would determine which path was used. But now since it's in a cache, it shows up at the same place every time! yay!)

2019-08-21 18:59 UTC, maplebed requested changes
I think we need to separate the `build_start` file in to a workspace and the binaries in to a versioned cache, then we'll be in good shape.

2019-08-21 19:01 UTC, maplebed commented on orb.yml
> +            # get all buildevenst binaries so jobs in any OS will work
```suggestion
            # get all buildevents binaries so jobs in any OS will work
```

2019-08-21 19:06 UTC, maplebed commented
I'm intrigued by the change from separate download / save / restore cache steps to one combined setup step. In the face of `watch_and_finish`, I wonder... does this mean the `setup` step containing `start_trace` is no longer necessary? Each job reattaches the cache with downloaded binaries (or downloads them if necessary). The `build_start` time isn't used with `watch`, and those are the only two things the `start_trace` step really does. Hmmm.... In that world, `start` is only necessary when you're going to later call `finish`. Wild!

2019-08-22 11:02 UTC, PChambino commented
I may have tried to come up with a solution that would work specifically for our use case where we use the `build_start` file to send intermediate durations to Honeycomb. But I believe it matches the requirements of the `finish` command as well.

Actually, with the combined `setup` command as I implemented, `start_trace` is not necessary by `finish` as well since the `build_start` file is created if it doesn't exist on each job. For now I will keep it around, but it may be worth considering if that command should be dropped.

I think the decision between using the workspace or using the cache is also about what do we want `finish` to report about the workflow duration when re-running only failed jobs. Do we want it to report the duration since the first workflow run, or reset it on every re-run of the workflow for failed jobs?

The first option will force us to use the workspace for the `build_start` file, but for the second option we can choose between the cache and the workspace. Also, the second option matches the behaviour of `watch` (right?) and using the cache would avoid any performance issues with the workspace since we need to check if the file exists on every job. So I would go for option 2 using a cache for the `build_start` file.

I have an idea on how to use the cache for the `build_start` and not download the binaries on every workflow run. Let me see if I can do it.

2019-08-22 11:13 UTC, PChambino commented
I may have tried to come up with a solution that would work specifically for our use case where we use the `build_start` file to send intermediate durations to Honeycomb. But I believe it matches the requirements of the `finish` command as well.

Actually, with the combined `setup` command as I implemented, `start_trace` is not necessary by `finish` as well since the `build_start` file is created if it doesn't exist on each job. For now I will keep it around, but it may be worth considering if that command should be dropped.

I think the decision between using the workspace or using the cache is also about what do we want `finish` to report about the workflow duration when re-running only failed jobs. Do we want it to report the duration since the first workflow run, or reset it on every re-run of the workflow for failed jobs?

The first option will force us to use the workspace for the `build_start` file, but for the second option we can choose between the cache and the workspace. Also, the second option matches the behaviour of `watch` (right?) and using the cache would avoid any performance issues with the workspace since we need to check if the file exists on every job. So I would go for option 2 using a cache for the `build_start` file.

I have an idea on how to use the cache for the `build_start` and not download the binaries on every workflow run. Let me see if I can do it.

2019-08-22 13:47 UTC, PChambino commented
Ok. It is done and I tested that it works as expected. I think this is the best solution in my opinion since it completely removes the need for the `start_trace` command for both the `watch` and `finish` commands, and the `finish` command reports the trace duration since the start of the current workflow even if it was re-run from failed, instead of reporting since the start of the first workflow of that commit. (This means we can drop the `start_trace` command, but I will let you decide if you think that is a good idea or not.)

How does it work? It uses two cache keys, one for the workflow and another for the binaries, but include the binaries on the workflow cache as well. Then we can fetch the workflow cache if it exists or the binaries cache.
I prefixed the binaries cache key with `3:` because the other key already includes the `build_start` file which we don't want (and it is 3, not 2 because I messed up with 2 on my end 😅).

2021-07-14 20:40 UTC, MikeGoldsmith commented
We’re going to close this for now as it has no recent activity. Feel free to re-open if it’s still relevant.

2021-07-14 20:40 UTC, closed without merging