enable cache busting
honeycombio/buildevents-orb pull request #42
Opened 2021-09-13 17:54 UTC by nelzkiddom

## Which problem is this PR solving?
I believe I somehow got something corrupted into my cache (maybe by jumping from one architecture to another?), and per CircleCI docs we need to use environment variables to bust caches nowadays (instead of having a button in the UI): https://support.circleci.com/hc/en-us/articles/115015426888-Clear-project-dependency-cache

## Short description of the changes
Enables orb end-users to bust the cache where the buildevents executables are kept.

2021-09-14 16:05 UTC, nelzkiddom commented
Ooh, even more info that shows WHY I need to bust cache: https://support.circleci.com/hc/en-us/articles/360056920051--Error-untarring-cache-when-running-a-macOS-job

2021-09-14 16:08 UTC, nelzkiddom commented
But that article maybe points towards also including an `{{ arch }}` in the cache name as well. Let me know if you'd like me to update with that!

2021-09-14 16:16 UTC, nelzkiddom commented
And now I'm spitballing... That above article then might indicate that Honeycomb wants to re-thinks the "download all 3 executables at once" strategy in the Orb... 🤔

2021-09-15 17:53 UTC, JamieDanielson commented
Thanks for the notes @nelzkiddom!
Hmm, looks like there is some research for us to do here. We'll add it to our list for review.

2021-09-21 18:26 UTC, JamieDanielson requested changes
Nice! Looks like this will be useful. A suggestion to instead append the environment variable based on the [examples](https://circleci.com/docs/2.0/caching/#full-example-of-saving-and-restoring-cache) provided by Circle.

2021-09-21 18:26 UTC, JamieDanielson commented on orb.yml
> +          key: buildevents{{ .Environment.BUILDEVENTS_CACHE_VERSION }}-v0.6.0
```suggestion
          key: buildevents-v0.6.0-{{ .Environment.BUILDEVENTS_CACHE_VERSION }}
```

2021-09-21 18:26 UTC, JamieDanielson commented on orb.yml
> +          key: buildevents{{ .Environment.BUILDEVENTS_CACHE_VERSION }}-v0.6.0
```suggestion
          key: buildevents-v0.6.0-{{ .Environment.BUILDEVENTS_CACHE_VERSION }}
```

2021-09-21 20:14 UTC, nelzkiddom commented
@JamieDanielson Suggestions applied!

2021-09-21 20:18 UTC, nelzkiddom commented
@JamieDanielson My only concern with the suggestions is that in Orb v0.3.0 the cache key is `buildevents-v0.6.0`, but anyone who bumps to the next version will automatically have the cache busted because the new default cache key is `buildevents-v0.6.0-` (notice the extra dash suffix).
This doesn't negatively affect me myself, but thought you might want to be aware of that impact.

2021-09-21 21:02 UTC, JamieDanielson requested changes
Hm, you may be right. Let's remove the extra hyphen just in case!

2021-09-21 21:02 UTC, JamieDanielson commented on orb.yml
> +          key: buildevents-v0.6.0-{{ .Environment.BUILDEVENTS_CACHE_VERSION }}
```suggestion
          key: buildevents-v0.6.0{{ .Environment.BUILDEVENTS_CACHE_VERSION }}
```

2021-09-21 21:02 UTC, JamieDanielson commented on orb.yml
> +          key: buildevents-v0.6.0-{{ .Environment.BUILDEVENTS_CACHE_VERSION }}
```suggestion
          key: buildevents-v0.6.0{{ .Environment.BUILDEVENTS_CACHE_VERSION }}
```

2021-09-21 21:06 UTC, nelzkiddom commented
@JamieDanielson Awesome. Done!

2021-09-22 14:00 UTC, JamieDanielson approved these changes

2021-09-22 14:01 UTC, merged